[package]
name = "echo-slack-bot-rs"
version = "0.1.6"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
futures-util = { version = "0.3", features = ["sink"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.27", features = ["native-tls"] }
tungstenite = { version = "0.27", features = ["url"] }
